### ISSUE TITLE
Mailgun EU region Domain error - Error.mailgun.send_email_failed: Failed to send email (Domain not found: mydomain.com)

### ISSUE THREAD

**Issue by resgurung** [vapor-community/VaporMailgunService#30]
When domain register in EU gives 

> Error.mailgun.send_email_failed: Failed to send email (Domain not found: mydomain.com)

Due to locked files in the packages and func declared public, i have extended the 

> Mailgun.swift

 class and created  
1. public func sendEU(_ content: Message, on container: Container) throws -> Future<Response> 
instead of 
2. public func send(_ content: Message, on container: Container) throws -> Future<Response>
with only changes to 
- let mailgunURL = "https://api.mailgun.net/v3/\(domain)/messages"
to 
- let mailgunURL = "https://api.eu.mailgun.net/v3/\(domain)/messages"

Also function 
- func encode(apiKey: String) throws -> String
- private func process(_ response: Response) throws -> Response

are within fileprivate extenison which i moved to mine extension so i can use it. 

It would be great if we can override either "func send" or property  mailgunURL. Thanks

**Comment by twof** [comment]
Fixed in https://github.com/vapor-community/VaporMailgunService/pull/31

**Comment by resgurung** [comment]
nice work guys, thanks
