### ISSUE TITLE
[ ERROR ] Abort.404: Not Found (ApplicationResponder.swift:50)

### ISSUE THREAD

**Issue by jobyid** [vapor-community/VaporMailgunService#36]
Hi, 
I have installed the package as described and copied the example router to send a test message via mailgun, but keep getting the same error. 

[ ERROR ] Abort.404: Not Found (ApplicationResponder.swift:50)

Any Ideas? 
I am pretty new to vapor and mailgun so I am sure its a simple mistake on my part, but I can't figure it out right now. 

Many Thanks 

Joby

**Comment by twof** [comment]
Hi! Thanks for reporting this issue. Can you share a code snippet demonstrating the error?

**Comment by jobyid** [comment]
Yeah sorry. 
Here is the router. 
`router.post("mail") { (req) -> Future<Response> in
        let message = Mailgun.Message(
            from: "Excited User <mailgun@mg.climbingwallmanager.com>",
            to: "joby@mg.climbingwallmanager.com",
            subject: "Hello",
            text: "Testing some Mailgun awesomness!"
            //html: "<h1>This is a newsletter</h1>"
        )

        let mailgun = try req.make(Mailgun.self)
        return try mailgun.send(message, on: req)
    }`
And the package.
`let package = Package(
    name: "cwmapi",
    dependencies: [
        // 💧 A server-side Swift web framework.
        .package(url: "https://github.com/vapor/vapor.git", .upToNextMinor(from: "3.3.0")),
        .package(url: "https://github.com/OpenKitten/MongoKitten.git", from: "5.0.0"),
        .package(url: "https://github.com/vapor/leaf.git", .upToNextMinor(from: "3.0.0")),
        .package(url: "https://github.com/twof/VaporMailgunService.git", from: "1.5.0")
    ],
    targets: [
        .target(name: "App", dependencies: ["Vapor", "MongoKitten", "Leaf", "Mailgun"]),
        .target(name: "Run", dependencies: ["App"]),
        .testTarget(name: "AppTests", dependencies: ["App"]),
    ]
)`
and config - api hidden. 

`let mailgun = Mailgun(apiKey: "xxxxxxxxxxxxxxx-xxxxxxxx-xxxxxx", domain: "mg.climbingwallmanager.com", region: .eu)
    services.register(mailgun, as: Mailgun.self)`

**Comment by twof** [comment]
Hmmm everything you've got here looks correct. Can you put a breakpoint or print under
`router.post("mail") { (req) -> Future<Response> in` for me to make sure your route is getting hit? 

How are you making requests to your vapor server?

**Comment by jobyid** [comment]
Yeah looks like it is not getting hit, I am using localhost:8080/ running it on my computer, other routers are working. Looking at it only the get routers seem to be working?

**Comment by twof** [comment]
@jobyid are you sending requests to your server using your browser, or are you using an http client like Postman or Paw?

**Comment by jobyid** [comment]
I’m using a browser, I tried Firefox and Chrome

**Comment by jobyid** [comment]
Ok so I have just tried it using Rested and it worked, so my appologies looks like by using the browser I was casuing my own issues. 
Thank you for your help.

**Comment by twof** [comment]
@jobyid ahhh yup that'll do it. Browsers only send GET requests. All good! Best of luck!

**Comment by RomanEmperor** [comment]
I am getting this issue as well. However, everything works, It just throws the error.

[ ERROR ] Abort.404: Not Found (ApplicationResponder.swift:50)

My Machine' details
`emperor@Romans-MacBook-Pro ~ % vapor --version
Vapor Toolbox: 3.1.10
emperor@Romans-MacBook-Pro ~ % 

Xcode: Version 11.4.1 (11E503a)

macOS Catalina 10.15.4
`

Here's my middleware registration 

`    // Register middleware
    var middlewares = MiddlewareConfig() // Create _empty_ middleware config
    middlewares.use(FileMiddleware.self) // Serves files from `Public/` directory
    middlewares.use(ErrorMiddleware.self) // Catches errors and converts to HTTP response
    services.register(middlewares)`

The middle ware is caught by breakpoint while booting / starting the server at localhost:8080

I have defined ` else {
                    throw Abort(.internalServerError)
                }`
in multiple places, when adding breakpoint seems. like these lines aren't throwing issues.

I am using Firefox, opera, and safari..
[Screen Recording 2020-04-26 at 11.07.34.zip](https://github.com/vapor-community/VaporMailgunService/files/4534690/Screen.Recording.2020-04-26.at.11.07.34.zip)
![Screenshot 2020-04-26 at 11 22 47](https://user-images.githubusercontent.com/16022010/80298899-46339180-87b0-11ea-9973-d8cfe618e780.png)
